"""Astro CMS Bridge for publishing content to static sites.

This module provides integration with Astro-based blogs for publishing
food content generated by FoodLog.

Features:
- Publish blog posts to Astro CMS
- Update existing posts
- Manage draft/published state
- Retrieve analytics for published content

Configuration:
- ASTRO_API_KEY: API key for Astro CMS
- ASTRO_ENDPOINT: Base URL of the Astro CMS API
"""

import os
from datetime import UTC, datetime
from typing import Any

import httpx


class AstroBridge:
    """Bridge to publish content to Astro-based blog."""

    def __init__(self):
        self.api_key = os.environ.get("ASTRO_API_KEY")
        # Normalize endpoint to avoid double slashes when building URLs
        raw_endpoint = os.environ.get("ASTRO_ENDPOINT", "")
        self.endpoint = raw_endpoint.rstrip("/") if raw_endpoint else ""
        self.enabled = bool(self.api_key and self.endpoint)

    async def publish_post(
        self,
        content: dict[str, Any],
        user_id: str,
        publish_immediately: bool = False,
    ) -> dict[str, Any]:
        """
        Publish content to Astro CMS.

        Args:
            content: Blog post content from ContentGeneratorAgent
            user_id: User ID for attribution
            publish_immediately: Whether to publish now or save as draft

        Returns:
            Result dict with success status, URL or draft ID, and published timestamp
        """
        if not self.enabled:
            return {
                "success": False,
                "error": "Astro bridge not configured. Set ASTRO_API_KEY and ASTRO_ENDPOINT.",
            }

        # Transform to Astro content collection format
        astro_content = {
            "title": content.get("title", "Untitled"),
            "slug": content.get("slug", "untitled"),
            "description": content.get("metadata", {}).get("description", ""),
            "pubDate": (datetime.now(UTC).isoformat() if publish_immediately else None),
            "draft": not publish_immediately,
            "author": user_id,
            "tags": content.get("metadata", {}).get("keywords", []),
            "body": content.get("content", ""),
        }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    f"{self.endpoint}/api/content",
                    json=astro_content,
                    headers={
                        "Authorization": f"Bearer {self.api_key}",
                        "Content-Type": "application/json",
                    },
                )

                if response.status_code in (200, 201):
                    data = response.json()
                    return {
                        "success": True,
                        "url": data.get("url"),
                        "post_id": data.get("id"),
                        "published_at": (datetime.now(UTC).isoformat() if publish_immediately else None),
                    }
                else:
                    # Include truncated response body for debugging
                    body_preview = response.text[:200] if response.text else ""
                    return {
                        "success": False,
                        "error": f"Astro API error: {response.status_code} - {body_preview}",
                    }
        except httpx.TimeoutException:
            return {"success": False, "error": "Request to Astro CMS timed out"}
        except httpx.RequestError as e:
            return {"success": False, "error": f"Network error: {str(e)}"}

    async def update_post(
        self,
        post_id: str,
        content: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Update an existing post in Astro CMS.

        Args:
            post_id: The ID of the post to update
            content: Updated content dict

        Returns:
            Result dict with success status
        """
        if not self.enabled:
            return {
                "success": False,
                "error": "Astro bridge not configured. Set ASTRO_API_KEY and ASTRO_ENDPOINT.",
            }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.patch(
                    f"{self.endpoint}/api/content/{post_id}",
                    json=content,
                    headers={
                        "Authorization": f"Bearer {self.api_key}",
                        "Content-Type": "application/json",
                    },
                )
                if response.status_code == 200:
                    return {"success": True, "post_id": post_id}
                # Include truncated response body for debugging
                body_preview = response.text[:200] if response.text else ""
                return {
                    "success": False,
                    "error": f"Failed to update post: {response.status_code} - {body_preview}",
                }
        except httpx.TimeoutException:
            return {"success": False, "error": "Request to Astro CMS timed out"}
        except httpx.RequestError as e:
            return {"success": False, "error": f"Network error: {str(e)}"}

    async def delete_post(
        self,
        post_id: str,
    ) -> dict[str, Any]:
        """
        Delete a post from Astro CMS.

        Args:
            post_id: The ID of the post to delete

        Returns:
            Result dict with success status
        """
        if not self.enabled:
            return {
                "success": False,
                "error": "Astro bridge not configured. Set ASTRO_API_KEY and ASTRO_ENDPOINT.",
            }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.delete(
                    f"{self.endpoint}/api/content/{post_id}",
                    headers={"Authorization": f"Bearer {self.api_key}"},
                )
                if response.status_code in (200, 204):
                    return {"success": True, "post_id": post_id}
                # Include truncated response body for debugging
                body_preview = response.text[:200] if response.text else ""
                return {
                    "success": False,
                    "error": f"Failed to delete post: {response.status_code} - {body_preview}",
                }
        except httpx.TimeoutException:
            return {"success": False, "error": "Request to Astro CMS timed out"}
        except httpx.RequestError as e:
            return {"success": False, "error": f"Network error: {str(e)}"}

    async def get_analytics(
        self,
        post_id: str,
    ) -> dict[str, Any]:
        """
        Get analytics for a published post.

        Args:
            post_id: The ID of the post

        Returns:
            Result dict with analytics data
        """
        if not self.enabled:
            return {
                "success": False,
                "error": "Astro bridge not configured. Set ASTRO_API_KEY and ASTRO_ENDPOINT.",
            }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(
                    f"{self.endpoint}/api/analytics/{post_id}",
                    headers={"Authorization": f"Bearer {self.api_key}"},
                )
                if response.status_code == 200:
                    return {"success": True, "analytics": response.json()}
                # Include truncated response body for debugging
                body_preview = response.text[:200] if response.text else ""
                return {
                    "success": False,
                    "error": f"Failed to fetch analytics: {response.status_code} - {body_preview}",
                }
        except httpx.TimeoutException:
            return {"success": False, "error": "Request to Astro CMS timed out"}
        except httpx.RequestError as e:
            return {"success": False, "error": f"Network error: {str(e)}"}


# Singleton instance
_astro_bridge: AstroBridge | None = None


def get_astro_bridge() -> AstroBridge:
    """Get or create the Astro bridge singleton."""
    global _astro_bridge
    if _astro_bridge is None:
        _astro_bridge = AstroBridge()
    return _astro_bridge
